wandb_version: 1

ep_rew_mean:
  desc: null
  value: null
total_timesteps:
  desc: null
  value: 0
iterations:
  desc: null
  value: 0
ep_len_mean:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.8.0
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702425411.381011
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.8.0
      5: 0.16.1
      8:
      - 5
      13: darwin-x86_64
